### ISSUE TITLE
[upstream] Browser console reports: "Assertion Failed: You modified "model.uid" twice..."

### ISSUE THREAD

**Issue by chris-hamper** [acquia/ember-drupal-waterwheel#6]
When viewing an article at `/article/{article-uuid}`, Chrome reports an error on the console similar to:
```Assertion Failed: You modified "model.uid" twice on <local-test@model:article::ember424:f66a387f-56a6-4f74-9684-3a701edd800a> in a single render. It was rendered in "template:local-test/templates/article.hbs" and modified in "template:local-test/templates/article.hbs". This was unreliable and slow in Ember 1.x and is no longer supported. See https://github.com/emberjs/ember.js/issues/13948 for more details.```

This is due to an upstream issue with Ember Data 2.14.x:
https://github.com/emberjs/data/issues/4942

As a temporary workaround, you can downgrade your project's `ember-data` library by running this in the project's root directory:
`npm install ember-data@2.13`

**Comment by jenter** [comment]
@chris-hamper I was running into this on image fields, are there any upcoming workarounds other than pinning this version to ember-data?

**Comment by chris-hamper** [comment]
@jenter Unfortunately not. The only workaround or fix I've come across is pinning the version. This seems to be a widespread issue (even Ember Observer appears to be running into it), so it will hopefully be addressed soon.

**Comment by jenter** [comment]
@chris-hamper makes sense, thanks for the update

**Comment by mmun** [comment]
We've released a [new version of ember data](https://github.com/emberjs/data/releases/tag/v2.14.10) that may fix this issue.

**Comment by jenter** [comment]
@mmun great news, I will test on our end and update this thread.

cc @danepowell @darkcody

**Comment by jenter** [comment]
@mmun great news, I confirmed the new version of ember data (2.14.10) fixes this issue. 
Thanks again for updating this in the loop!!

cc @chris-hamper @danepowell @darkcody
